version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    ports:
      # local->container
      - 27017:27017
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db

  # Node api service
  api:
    build:
      context: ./packages/service1
    ports:
      # local->container
      - 3000:3000
    environment:
      PORT: 3000
      MONGODB_URL: mongodb://mongo_db:27017
      DB_NAME: sample-db
    depends_on: 
      - mongo_db
    restart: always

volumes:
  mongo_data: {}