kind: StorageClass
apiVersion: storage.k8s.io/v1
provisioner: ebs.csi.aws.com
metadata:
  name: gp3-persistent-1b
parameters:
  type: gp3
reclaimPolicy: Retain
allowVolumeExpansion: true
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.ebs.csi.aws.com/zone
        values:
          - eu-west-1b
