---
# https://external-secrets.io/latest/api/clustersecretstore/
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.region }}
